version: "3.7"

services:
  server:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    restart: unless-stopped
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:

